# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10f0672b007758643188477bd702c78751362c97928cbfac8d3ab64998466d96cab59b21db26050cdd4c4053b7dee2b0cfa4f8a9a19e1b060b6fb706acea0a14

test:
  secret_key_base: 7a9b5308a5956aeb3e076209ef2d42ba5138a9b925cfd1ba9a1853969eed969258e5533246d0707a9bc4b9991563f42635e5751a1cc9e7e6d4036518b8de3e81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
